server:
  port: 9000

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: news-app
          uri: http://localhost:8080
          predicates:
            - Path= /user/**
          filters:
            - StripPrefix=1
        - id: favorite-service
          uri: http://localhost:8081
          predicates:
            - Path= /api/news/**
          filters:
            - StripPrefix=1
        - id: api-service
          uri: http://localhost:8082
          predicates:
            - Path= /news/**
          filters:
            - StripPrefix=1
